version: '3.6'
services:
    api:
        container_name: api_container
        image: teamoceancode/express-mongo-app
        environment:
            - PORT=${PORT}
            - NODE_ENV=development
            - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db/demo-app?authSource=admin
        ports:
            - ${PORT}:3000
        command: npm run start
        networks:
            - app_network

    db:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - 27017:27017
        volumes:
            - mongodata:/data/db/
        networks:
            - app_network

networks:
    app_network:
volumes:
    mongodata: